name: 'Upload to Qiniu'
description: 'Upload a file to Qiniu'
inputs:
  access_key:
    description: 'Access Key'
    required: true
  secret_key:
    description: 'Secret Key'
    required: true
  bucket_name:
    description: 'Name of the bucket'
    required: true
  key:
    description: 'Key of the file'
    required: true
  localfile:
    description: 'Path of the local file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qiniu
      shell: bash

    - name: Run script
      run: |
        python ${{ github.action_path }}/upload_to_qiniu.py --access_key ${{ inputs.access_key }} --secret_key ${{ inputs.secret_key }} --bucket_name ${{ inputs.bucket_name }} --key ${{ inputs.key }} --local_file ${{ inputs.local_file }}
      shell: bash
